version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    container_name: cargoiq-api

  dashboard:
    build: .
    command: ["streamlit", "run", "frontend/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    ports:
      - "8501:8501"
    container_name: cargoiq-dashboard
    depends_on:
      - api
